url: http://www.toadworld.co.uk
name: ToadWorld Fiction
description: Thinking of a different world
collections:
  stories:
    output: false
    permalink: /stories/:path/
  standalone_stories:
    output: false
    permalink: /stories/:path/
